name: jaeger

ports:
  - port: 6831
    protocol: UDP
    targetPort: 6831
  - port: 8889
    targetPort: 8889


container:
  image: otel/opentelemetry-collector-contrib
  args:
  - --config
  - /etc/otelcol/otel-collector-config.yml
  imageVersion: 0.109.0
  name: jaeger
  ports: 
  - containerPort: 6831
    protocol: UDP
  - containerPort: 8889

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config

  - name: otel-collector-config.yml
    mountPath: /etc/otelcol/otel-collector-config.yml
    value: otel-collector-config
