FROM alpine

RUN apk update
RUN apk add --no-cache iperf3 openrc bind-tools
COPY services/iperf3-client.service.sh /etc/init.d/iperf3-client
RUN chmod 0755 /etc/init.d/iperf3-client
RUN rc-update add devfs boot
RUN rc-update add procfs boot
RUN rc-update add sysfs boot
RUN rc-update add iperf3-client boot
RUN rm -rf /var/cache/apk/*
ENTRYPOINT ["/bin/sh", "-c", "echo sleeping; sleep 60; echo waking; ip=$(dig +short A iperf3); echo $ip; iperf3 -c $ip -t 300 -P 16"]
