FROM otel/opentelemetry-collector-contrib:0.109.0 AS builder

FROM alpine

RUN apk update
RUN apk add --no-cache openrc
COPY services/otelcol.service.sh /etc/init.d/otelcol
RUN chmod 0755 /etc/init.d/otelcol
COPY config/otel-collector-config-connector.yml /etc/otelcol/otel-collector-config.yml
COPY --from=builder /otelcol-contrib /otelcol-contrib
COPY --from=builder /etc/ssl/certs /etc/ssl/certs
RUN rc-update add devfs boot
RUN rc-update add procfs boot
RUN rc-update add sysfs boot
RUN rc-update add otelcol boot
RUN rm -rf /var/cache/apk/*

ENTRYPOINT ["/otelcol-contrib"]
CMD ["--config", "/etc/otelcol/otel-collector-config.yml"]
