FROM memcached:alpine

USER root
RUN apk add --no-cache openrc
COPY services/memcached.service.sh /etc/init.d/memcached
RUN chmod 0755 /etc/init.d/memcached
RUN rc-update add devfs boot
RUN rc-update add procfs boot
RUN rc-update add sysfs boot
RUN rc-update add memcached boot
RUN rm -rf /var/cache/apk/*
