FROM redis:alpine

RUN apk add --no-cache openrc
COPY services/redis.service.sh /etc/init.d/redis
RUN chmod 0755 /etc/init.d/redis
RUN rc-update add devfs boot
RUN rc-update add procfs boot
RUN rc-update add sysfs boot
RUN rc-update add redis boot
RUN rm -rf /var/cache/apk/*
