FROM alpine

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.9/main' >> /etc/apk/repositories
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.9/community' >> /etc/apk/repositories
RUN apk update
RUN apk add --no-cache mongodb openrc
COPY services/mongo.service.sh /etc/init.d/mongodb
RUN chmod 0755 /etc/init.d/mongodb
RUN rc-update add devfs boot
RUN rc-update add procfs boot
RUN rc-update add sysfs boot
RUN rc-update add mongodb boot
RUN rm -rf /var/cache/apk/*
